name: Edit release tag

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: New project release tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Say a polite hello"
        run: echo "$Greeting $First_Name, and welcome to the release tag actions script. :)"  

      - name: Checkout main (or master)
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      