name: Edit release tag

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: New project release tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Say a polite hello"
        run: echo "$GREETING $FIRST_NAME, and welcome to the release tag actions script. :)"  
        env:
          GREETING: ${{ vars.GREETING }}
          FIRST_NAME: ${{ vars.FIRST_NAME }}

      - name: Checkout main (or master)
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      